name: Automatic update

jobs:
  auto_update:
    name: Automatic update
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Automatic update"
        git config --local --unset-all "http.https://github.com/.extraheader"
        ./download.sh
        git push
on:
  push:
  pull_request:
  schedule:
  - cron:  '*/5 * * * *'
